//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALARm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class alerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal alerts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALARm.alerts", typeof(alerts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дистанция.
        /// </summary>
        public static string adm_distance {
            get {
                return ResourceManager.GetString("adm_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорога.
        /// </summary>
        public static string adm_road {
            get {
                return ResourceManager.GetString("adm_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, для начала заполните родительскую таблицу.
        /// </summary>
        public static string before_insert {
            get {
                return ResourceManager.GetString("before_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, для начала ввода заполните таблицу периодов действия.
        /// </summary>
        public static string before_insert_period {
            get {
                return ResourceManager.GetString("before_insert_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, для начала заполните таблицу путей.
        /// </summary>
        public static string before_insert_track {
            get {
                return ResourceManager.GetString("before_insert_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проверьте корректность вводимых данных .
        /// </summary>
        public static string check_fields_filling {
            get {
                return ResourceManager.GetString("check_fields_filling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руководитель.
        /// </summary>
        public static string chief_full_name {
            get {
                return ResourceManager.GetString("chief_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс.
        /// </summary>
        public static string class_ {
            get {
                return ResourceManager.GetString("class_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вводимые данные пересекаются с имеющимися.
        /// </summary>
        public static string coord_overlaps {
            get {
                return ResourceManager.GetString("coord_overlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата начала действия должна быть меньше даты окончания действия.
        /// </summary>
        public static string date_overlaps {
            get {
                return ResourceManager.GetString("date_overlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление....
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось изменить запись.
        /// </summary>
        public static string edit_error {
            get {
                return ResourceManager.GetString("edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение.
        /// </summary>
        public static string editing {
            get {
                return ResourceManager.GetString("editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблица пустая.
        /// </summary>
        public static string empty_table {
            get {
                return ResourceManager.GetString("empty_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сделать экспорт.
        /// </summary>
        public static string export_error {
            get {
                return ResourceManager.GetString("export_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, заполните все поля.
        /// </summary>
        public static string filling_error {
            get {
                return ResourceManager.GetString("filling_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец (км).
        /// </summary>
        public static string final_km {
            get {
                return ResourceManager.GetString("final_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец (м).
        /// </summary>
        public static string final_m {
            get {
                return ResourceManager.GetString("final_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участок дистанции.
        /// </summary>
        public static string frm_distance_caption {
            get {
                return ResourceManager.GetString("frm_distance_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось генерировать путевой лист.
        /// </summary>
        public static string generate_list_error {
            get {
                return ResourceManager.GetString("generate_list_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сделать импорт.
        /// </summary>
        public static string import_error {
            get {
                return ResourceManager.GetString("import_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить запись .
        /// </summary>
        public static string insert_error {
            get {
                return ResourceManager.GetString("insert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление записи.
        /// </summary>
        public static string inserting {
            get {
                return ResourceManager.GetString("inserting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Километр.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина.
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует направления.
        /// </summary>
        public static string NoDirection {
            get {
                return ResourceManager.GetString("NoDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нестандартные километры.
        /// </summary>
        public static string nonstandard_km {
            get {
                return ResourceManager.GetString("nonstandard_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует станции.
        /// </summary>
        public static string NoStations {
            get {
                return ResourceManager.GetString("NoStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует главные пути.
        /// </summary>
        public static string NoTracks {
            get {
                return ResourceManager.GetString("NoTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить эту запись?.
        /// </summary>
        public static string remove_ask {
            get {
                return ResourceManager.GetString("remove_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало (км).
        /// </summary>
        public static string start_km {
            get {
                return ResourceManager.GetString("start_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало (м).
        /// </summary>
        public static string start_m {
            get {
                return ResourceManager.GetString("start_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция выполнена успешно.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
    }
}
