//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALARm.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALARm.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АРЗ.
        /// </summary>
        internal static string AnomalisticGap {
            get {
                return ResourceManager.GetString("AnomalisticGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котлом.
        /// </summary>
        internal static string Boiler {
            get {
                return ResourceManager.GetString("Boiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уш.
        /// </summary>
        internal static string Broadening {
            get {
                return ResourceManager.GetString("Broadening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Излом упруой клемми.
        /// </summary>
        internal static string BrokenArsClamp {
            get {
                return ResourceManager.GetString("BrokenArsClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to излом подкладки.
        /// </summary>
        internal static string BrokenBasePlate {
            get {
                return ResourceManager.GetString("BrokenBasePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to излом закладных болтов.
        /// </summary>
        internal static string BrokenMainBolts {
            get {
                return ResourceManager.GetString("BrokenMainBolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клемма под подошвой рельса.
        /// </summary>
        internal static string ClampUnderRail {
            get {
                return ResourceManager.GetString("ClampUnderRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суж.
        /// </summary>
        internal static string Constriction {
            get {
                return ResourceManager.GetString("Constriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие скрепления.
        /// </summary>
        internal static string D65_NoPad {
            get {
                return ResourceManager.GetString("D65_NoPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ст.
        /// </summary>
        internal static string Degree3 {
            get {
                return ResourceManager.GetString("Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямой.
        /// </summary>
        internal static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пу.л..
        /// </summary>
        internal static string DownhillLeft {
            get {
                return ResourceManager.GetString("DownhillLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пу.п..
        /// </summary>
        internal static string DownhillRight {
            get {
                return ResourceManager.GetString("DownhillRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пр.л.
        /// </summary>
        internal static string DrawdownLeft {
            get {
                return ResourceManager.GetString("DrawdownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пр.п.
        /// </summary>
        internal static string DrawdownRight {
            get {
                return ResourceManager.GetString("DrawdownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS.
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СЗ.
        /// </summary>
        internal static string FusingGap {
            get {
                return ResourceManager.GetString("FusingGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З.
        /// </summary>
        internal static string Gap {
            get {
                return ResourceManager.GetString("Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ш10.
        /// </summary>
        internal static string Gauge10 {
            get {
                return ResourceManager.GetString("Gauge10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие скрепления.
        /// </summary>
        internal static string GBRNoPad {
            get {
                return ResourceManager.GetString("GBRNoPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИН.л.
        /// </summary>
        internal static string ImpulsLeft {
            get {
                return ResourceManager.GetString("ImpulsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИН.п.
        /// </summary>
        internal static string ImpulsRight {
            get {
                return ResourceManager.GetString("ImpulsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие болта.
        /// </summary>
        internal static string KB65_MissingClamp {
            get {
                return ResourceManager.GetString("KB65_MissingClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие скрепления.
        /// </summary>
        internal static string KB65_NoPad {
            get {
                return ResourceManager.GetString("KB65_NoPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие болта.
        /// </summary>
        internal static string KD65NB {
            get {
                return ResourceManager.GetString("KD65NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КНС.
        /// </summary>
        internal static string KNS {
            get {
                return ResourceManager.GetString("KNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие скрепления.
        /// </summary>
        internal static string KppNoPad {
            get {
                return ResourceManager.GetString("KppNoPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДВ.л.
        /// </summary>
        internal static string LongWaveLeft {
            get {
                return ResourceManager.GetString("LongWaveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДВ.п.
        /// </summary>
        internal static string LongWaveRight {
            get {
                return ResourceManager.GetString("LongWaveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СВ.л.
        /// </summary>
        internal static string MiddleWaveLeft {
            get {
                return ResourceManager.GetString("MiddleWaveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СВ.п.
        /// </summary>
        internal static string MiddleWaveRight {
            get {
                return ResourceManager.GetString("MiddleWaveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отсутствие двух или более пришивочных костылей.
        /// </summary>
        internal static string Missing2OrMoreMainSpikes {
            get {
                return ResourceManager.GetString("Missing2OrMoreMainSpikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отсутствие упругой клеммы.
        /// </summary>
        internal static string MissingArsClamp {
            get {
                return ResourceManager.GetString("MissingArsClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MissingClamp {
            get {
                return ResourceManager.GetString("MissingClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рнр.
        /// </summary>
        internal static string NoneStrightening {
            get {
                return ResourceManager.GetString("NoneStrightening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рн.
        /// </summary>
        internal static string NoneStrigtSide {
            get {
                return ResourceManager.GetString("NoneStrigtSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие болта.
        /// </summary>
        internal static string P350MissingClamp {
            get {
                return ResourceManager.GetString("P350MissingClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oтв.ш.
        /// </summary>
        internal static string PatternRetraction {
            get {
                return ResourceManager.GetString("PatternRetraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пси.
        /// </summary>
        internal static string Psi {
            get {
                return ResourceManager.GetString("Psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?Пси.
        /// </summary>
        internal static string PsiNear {
            get {
                return ResourceManager.GetString("PsiNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укл.
        /// </summary>
        internal static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?Уkл.
        /// </summary>
        internal static string RampNear {
            get {
                return ResourceManager.GetString("RampNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ип.л.
        /// </summary>
        internal static string ReducedWearLeft {
            get {
                return ResourceManager.GetString("ReducedWearLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ип.п.
        /// </summary>
        internal static string ReducedWearRight {
            get {
                return ResourceManager.GetString("ReducedWearRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратный.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П.
        /// </summary>
        internal static string Sag {
            get {
                return ResourceManager.GetString("Sag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КВ.л.
        /// </summary>
        internal static string ShortWaveLeft {
            get {
                return ResourceManager.GetString("ShortWaveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КВ.п.
        /// </summary>
        internal static string ShortWaveRight {
            get {
                return ResourceManager.GetString("ShortWaveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иб.л.
        /// </summary>
        internal static string SideWearLeft {
            get {
                return ResourceManager.GetString("SideWearLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иб.п.
        /// </summary>
        internal static string SideWearRight {
            get {
                return ResourceManager.GetString("SideWearRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие скрепления.
        /// </summary>
        internal static string SklNoPad {
            get {
                return ResourceManager.GetString("SklNoPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анп.
        /// </summary>
        internal static string SpeedUp {
            get {
                return ResourceManager.GetString("SpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?Анп.
        /// </summary>
        internal static string SpeedUpNear {
            get {
                return ResourceManager.GetString("SpeedUpNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Р.
        /// </summary>
        internal static string Strightening {
            get {
                return ResourceManager.GetString("Strightening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Р.
        /// </summary>
        internal static string StrighteningLeft {
            get {
                return ResourceManager.GetString("StrighteningLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Р.
        /// </summary>
        internal static string StrighteningRight {
            get {
                return ResourceManager.GetString("StrighteningRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нпк.л.
        /// </summary>
        internal static string TreadTiltLeft {
            get {
                return ResourceManager.GetString("TreadTiltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нпк.п.
        /// </summary>
        internal static string TreadTiltRight {
            get {
                return ResourceManager.GetString("TreadTiltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ив.л.
        /// </summary>
        internal static string VertIznosL {
            get {
                return ResourceManager.GetString("VertIznosL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ив.п.
        /// </summary>
        internal static string VertIznosR {
            get {
                return ResourceManager.GetString("VertIznosR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствие упругой клеммы.
        /// </summary>
        internal static string WW {
            get {
                return ResourceManager.GetString("WW", resourceCulture);
            }
        }
    }
}
